version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    environment:
      DYNAMODB_ENDPOINT: "http://dynamodb:8000"
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
      REGION_NAME: "us-west-2"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data

volumes:
  dynamodb_data: